#!/bin/bash

echo "running 'brew update; brew upgrade; brew cask upgrade'"
brew update; brew upgrade; brew cask upgrade --greedy

echo "cleanup of packages except python"
brew_packages_to_be_cleaned=`brew list -1 | grep -vi python | tr '\n' ' '`
brew cleanup $brew_packages_to_be_cleaned

echo "cleanup of casks"
brew_cask_packages_to_be_cleaned=`brew cask list -1 | tr '\n' ' '`
brew cleanup $brew_cask_packages_to_be_cleaned

echo "upgrading oh-my-zsh"
~/.oh-my-zsh/tools/upgrade.sh
source ~/.zshrc
