#!/bin/bash

# clean up git branches older than 6 months

for gitRepo in $(find ~/git -name ".git" | sed 's/.git$//g'); do
  cd $gitRepo
  for branch in $(git branch | grep -v master | grep -v HEAD | sed /\*/d); do
    if [[ "$(git log $branch --since='6 months ago' | wc -l)" -eq 0 ]]; then
      echo "deleting $gitRepo:$branch"
      git branch -D $branch
    fi
  done
  git gc
done
cd
