#!/bin/bash

msg=$1
amend=$2

if [[ $amend != "" ]]; then
  if [[ $amend != "--amend" ]]; then
    echo "uhh!! I don't know what to do with $amend"
    exit 1
  fi
fi

if [[ $msg == "" ]]; then
  echo "Please enter a commit message."
  exit 1
fi

uncommittedFiles=`git status | grep "Changes not staged for commit" | wc -l | tr -d '[:space:]'`
if [[ $uncommittedFiles != "0" ]]; then
  echo "There are files that have been modified but not added. Are you sure you want to continue in the current state? (y/n)"
  read goAhead
  if [[ $commitGoAhead != 'y' ]]; then
    echo "Cancelled.."
    exit -1
  fi
fi

stylecheck=0
if [[ -e "scalastyle-config.xml" ]]; then
  sbt -mem 1700 compile test scalafmt test:scalafmt scalastyle test:scalastyle
  stylecheck=$?
fi

if [[ $stylecheck == 0 ]]; then
  git commit $amend -m "$msg"
else
  echo "Stylecheck or compile failed. Please entertain the belligerent requests of the mechanical code parsers."
fi
