#!/bin/bash

branch=`git rev-parse --abbrev-ref HEAD`
if [[ $branch != "master" ]]; then
  echo "Please switch to master branch."
  exit 0
fi

git fetch upstream master && git merge upstream/master && git push origin master